# Introduction

Ice-marginal lakes are located adjacent to glaciers, commonly forming at glacier termini, tributary junctions, along glacier margins, or where glacially eroded bedrock or sediment creates topographic depressions (overdeepenings; Carrivick and Tweed, 2013; Cook and Quincey, 2015). These lakes can impact human societies in a multitude of ways, ranging from water resources (Immerzeel et al., 2020) and tourist attractions (Wang and Zhou, 2019; Welling et al., 2020) to destructive and lethal hazards (Carrivick and Tweed, 2016; Cook et al., 2016; Emmer, 2017). Formation or drainage of lakes can impact ecosystem dynamics by providing or removing a source of stored freshwater, altering the sediment flux within a basin, creating new habitat (e.g., Milner et al., 2008), or altering downstream flow characteristics (Tweed and Carrivick, 2015; Jacquet et al., 2017).  Glacial lake outburst floods (GLOFs; when a lake dam fails or is overtopped; Clague and Evans, 2000) from ice-marginal lakes can have massive impacts on downstream river channel morphology and sediment supply (e.g., Jacquet et al., 2017), disrupt ecosystems (e.g., Meerhoff et al., 2018), destroy infrastructure, and cause the loss of human lives (e.g., Carrivick and Tweed, 2016). Time-varying inventories of ice-marginal lakes are a critical first step in predicting future lake evolution and assessing GLOF hazards.

Global (Shugar et al., 2020) and regional (Wang et al., 2013; Carrivick and Quincey, 2014; Glasser et al., 2016; Nie et al., 2017; Song et al., 2017; Emmer et al., 2020) lake inventories document recent increases in ice-marginal lakes, however, many studies report solely on the change in total frequency and cumulative area of lakes within the study region, or consider only one type of lake (e.g., moraine-dammed or ice-dammed). By not accounting for individual lake characteristics and individual lake changes through time, important trends could be aliased and limits the understanding of processes controlling area change. For example, if a subset of lakes grow while other lakes drain, the positive and negative growth will offset one another, and the overall lake frequency and area change would be small and therefore misleading. Alternatively, if a few large lakes dominate the documented area change for a region, applying the regionally-averaged lake growth to all lakes would overestimate growth, therefore preventing an accurate physical understanding of this change. In addition, the ecological consequences of lake changes may differ based on where lake growth occurs: a change from no lake to a 1 km^2^ lake could have larger ecological and hazard implications than a large lake (e.g., >10 km^2^) expanding by a few square kilometers (Dorava and Milner, 2000). Cumulative regional studies provide a first-order estimate of regional changes, however, individual lake change must be analyzed to develop a process-based understanding of area change in order to predict future lake growth and watershed-scale impacts.

Recent studies parse lakes by characteristics which predict lake behavior, such as dam type and evolution phase (Emmer et al., 2015, 2020), or the spatial relationship to their source glacier (e.g., proglacial, supraglacial, unconnected, detached; Nie et al., 2017; Rounce et al., 2017; Chen et al., 2021). In the Himalaya, proglacial lakes (located at the glacier terminus, in contact with ice) contributed to 83% of the total lake area increase from 1990 to 2015, while only composing 55% of the lake population (Nie et al., 2017).  In this same region, supraglacial lakes (located on debris-covered glacier surfaces) experienced the greatest percent increase in area (367%) since 1990, though they only constitute 1.2% of total lake area in 2015 (Nie et al., 2017). Himalayan proglacial lakes tend to be persistent and contribute the most to regional area growth, whereas supraglacial lakes are small and experience large spatio-temporal variation in area and location (Nie et al., 2017; Rounce et al., 2017; Chen et al., 2021). In the Cordillera Blanca of Peru, many lakes shifted from proglacial to detached (no longer in contact with ice) and the dominant dam type for proglacial lakes shifted from moraine-dammed in 1948 to bedrock-dammed in 2017 (Emmer et al., 2020). In both the Himalaya and the Cordillera Blanca, dam type and lake position help characterize lake behavior; this variability would be lost if only cumulative changes were reported. These studies support the inclusion of dam type and topological position (used throughout to indicate spatial relationship of lakes to their source glacier) in comprehensive regional ice-marginal lake studies.

Alaska’s large glacier extent (86,723 km^2^; second largest area outside the ice sheets; Fig. 1; Kienholz et al., 2015; Zemp et al., 2019) and recent retreat (Larsen et al., 2015) allow for the presence of many ice-marginal lakes, while a wide range of climate zones (maritime, transitional, continental, and Arctic; Miller et al., 1999), glacier morphologies (valleys, cirques, debris, icefields) and bedrock lithologies/surficial deposits (Wilson et al., 2015) lead to a variety of lake characteristics (e.g., dam type and topological position; Fig. 1). Two unique aspects of the Alaska region are the numerous large, low-elevation coastal lakes (e.g., Bear Glacier Lake, Malaspina Lake, Grand Plateau Glacier Lake), and that lakes tend to be larger than ice-marginal lakes found around the world (e.g., High Mountain Asia, Central Europe, and Alaska have median lake areas of 0.11 km^2^, 0.11 km^2^, and 0.17 km^2^, respectively; Shugar et al., 2020). In addition, the lakes in this region are quite dynamic, as both the largest number and highest frequency of recorded GLOFs globally have occurred here, accounting for 25% of all recorded historical events (Carrivick and Tweed, 2016). 

<br>

![Distribution of glaciers as mapped by the Randolph Glacier Inventory (RGI Consortium, 2017) and subregions used to separate glaciated areas in Alaska and NW Canada (basemap provided by ESRI, 2021). Total glacier area (km^2^) and percent debris cover (percent of glacier surface covered by debris; Herreid and Pellicciotti, 2020) are displayed for each subregion.](.\images/f01.jpg)

</br>

Previous studies of glacial lakes in Alaska have examined ice-dammed lakes (Post and Mayo, 1971; Wolfe et al., 2014), a subset of ice-marginal lakes (Field et al., 2021), individual case studies (e.g., Sturm and Benson, 1985; Anderson et al., 2003; Pelto et al., 2013; Kienholz et al., 2020), or as a regional subset within a global study (Shugar et al., 2020). These studies are limited in their ability to comprehensively characterize regional trends for all lakes. Glaciers in this region are losing mass on the order of –75 Gt/yr (Larsen et al., 2015; Zemp et al., 2019), which represents the largest mass change and one of the highest specific mass changes for any region of the world. This change underscores the need for a time-varying lake inventory, given that ice-marginal lakes with different dam types and topological positions respond differently to glacier mass loss (e.g., Field et al., 2021). 

## Study Aims

The aims of the current study are to systematically inventory and characterize all ice-marginal lakes in Alaska using Landsat satellite imagery between 1984 and 2019. We aim to: (i) characterize ice-marginal lakes and decadal scale lake area change in Alaska; (ii) determine whether factors such as dam type, topological position, and region can characterize area change; and (iii) explore the interplay between the spatial distribution of lakes and regional characteristics such as glacier area, glacier complexity, and debris cover. 
