# Conclusions

As the second largest glacierized region outside the ice sheets, characterizing Alaska’s ice-marginal lakes and their evolution has important implications for glacier mass balance, ecosystem dynamics, and GLOF hazards. Varying topographic settings (valleys, cirques, debris, icefields) and a wide range of glacier complexities allow for an abundance of ice-marginal lakes of varying dam type and position. Overall, ice-marginal lakes in Alaska have grown in both number (+183 lakes, 38% increase) and area (+483 km^2^, 59% increase) between 1984–1988 and 2016–2019, though 56% of inventoried lakes did not experience detectable change. We demonstrate that lakes with different dam types and positions relative to their source glacier behave differently. Moraine-dammed, proglacial lakes experienced the largest growth likely due to clean-ice glacier retreat, while ice-dammed lakes experienced an overall loss in both number and area, likely due to thinning or disappearance of ice dams. Our study highlights the value of parsing ice marginal lakes by dam type and location in comprehensive ice-marginal lake studies to clarify important lake dynamics that are obscured by coarser regional averages. A clear understanding of which lakes are growing, and which are shrinking, as quantified here in a classified multitemporal ice-marginal lake inventory, is a crucial first step to understanding the drivers of historic change, predicting future lake evolution, and assessing GLOF hazard potential in icy mountainous regions.  
